function getDicSysName(_dictionary) {
var _dictionary = this.dictionary;
return "src=" + _dictionary.source.code + "&" + "dst=" + _dictionary.target.code;
}
function getUrl(_dictionary, _word) {
return _dictionary.rootUrl + "/api?q=" + _word + "&" + window[ _dictionary.getDicSysName ].bind(this).call();
}
function getArticle(_dictionary, _index) {

    var _article = _dictionary.initialState;
    var _query = _article.correct_query;

    if (_query) {

        var _str = "";
        var _match, _translation, _example;
        var _i, _j, _k;

            if (_article.exact_matches) {

                for (_i = 0; _i < _article.exact_matches.length; _i += 1) {
				_match = _article.exact_matches[_i];
                    _str += "<p class='exact_match'>" + _match.text + "<span class='word_type'> " + _match.word_type.pos + "</span></p>\r\n";
                    for (_j = 0; _j < _match.translations.length; _j += 1) {
                    _translation = _match.translations[_j];
                        _str += "<li class='translation'>" + _translation.text + "<span class='word_type'> " + _match.word_type.pos + "</span></li>\r\n";
                        for (_k = 0; _k < _translation.examples.length; _k += 1) {
                        _example = _translation.examples[_k];
                            _str += "<p class='example'><span class='source'>" + _example.source + "</span> — <span class='target'>" + _example.target + "</span></p>\r\n";
                        }
                    }
                }

            }
            if (_article.real_examples) {

				var _replaceText = "<span class='correct_query'>" + _query + "</span>";

				_str += "<div class='real_examples'>\r\n";

                for (_i = 0; _i < _article.real_examples.length; _i += 1) {
					_example = _article.real_examples[_i];
                    _str += "<p class='src'>" + _example.src.replace(/\[...\]/g, "").replace(_query, _replaceText) + "</p>\r\n"
                          + "<p class='dst'>" + _example.dst.replace(/\[...\]/g, "") + "</p>\r\n"
                          + "<p class='url'>" + _example.url + "</p>\r\n";
                }

				_str += "</div>\r\n";

            }
            this.responseArticle = _str + "<div id='Linguee'>© Linguee Dictionary, " + "2018" + ".</br>"
                    					+ "This page has been generated by a script and is likely to not fully reflect the original source.</br>"
										+ "Original url: https://www.linguee.com/"
										+ _dictionary.source.name + "-" + _dictionary.target.name
										+ "/search?source=auto&query=" + _query
										+ "</div>";

    return "S_OK";
    }
    this.responseArticle = this.HTML.NOT_FOUND;

return "NOT_FOUND";
}